"""empty message

Revision ID: 012740dfeb0b
Revises: 
Create Date: 2021-11-13 11:26:24.482736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012740dfeb0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('current_amount', sa.Integer(), nullable=True))
    op.drop_column('collections', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('collections', 'current_amount')
    # ### end Alembic commands ###
