"""empty message

Revision ID: 1f6392cfe314
Revises: cb02b37b1c19
Create Date: 2021-11-07 19:37:01.274568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6392cfe314'
down_revision = 'cb02b37b1c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
