"""empty message

Revision ID: 240446fdb824
Revises: 1a3888629738
Create Date: 2021-11-10 10:09:26.836806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240446fdb824'
down_revision = '1a3888629738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporter_email'), 'reporter', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporter_email'), table_name='reporter')
    op.drop_table('reporter')
    # ### end Alembic commands ###
