"""transactions

Revision ID: 711b327cdf9b
Revises: 41dc7c5def3e
Create Date: 2021-11-04 21:55:52.465633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711b327cdf9b'
down_revision = '41dc7c5def3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
