"""empty message

Revision ID: ac0fcb11516b
Revises: 582d6663135b
Create Date: 2021-10-06 22:43:22.047574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0fcb11516b'
down_revision = '582d6663135b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collector_users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_collector_users_email'), 'collector_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collector_users_email'), table_name='collector_users')
    op.drop_column('collector_users', 'is_admin')
    # ### end Alembic commands ###
