"""empty message

Revision ID: c92b2d8834bc
Revises: 
Create Date: 2021-10-09 14:52:09.545226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92b2d8834bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('usersurname', sa.String(length=64), nullable=False),
    sa.Column('useremail', sa.String(length=64), nullable=False),
    sa.Column('userphone', sa.String(length=32), nullable=True),
    sa.Column('userpassword', sa.String(length=128), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_useremail'), 'users', ['useremail'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_user_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('finish_count', sa.Integer(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modify', sa.DateTime(), nullable=False),
    sa.Column('is_end', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['collector_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collections_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collections_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_useremail'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
