"""empty message

Revision ID: cb02b37b1c19
Revises: 41dc7c5def3e
Create Date: 2021-11-07 19:30:35.487678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb02b37b1c19'
down_revision = '41dc7c5def3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('amount', sa.Integer(), nullable=False))
    op.drop_index('index_email', table_name='reporter')
    op.create_index(op.f('ix_reporter_email'), 'reporter', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporter_email'), table_name='reporter')
    op.create_index('index_email', 'reporter', ['email'], unique=False)
    op.drop_column('collections', 'amount')
    # ### end Alembic commands ###
