"""empty message

Revision ID: d126dd5b794f
Revises: 240446fdb824
Create Date: 2021-11-10 15:23:56.590722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd126dd5b794f'
down_revision = '240446fdb824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('current_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'current_amount')
    # ### end Alembic commands ###
